[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.80
blur = true

[mouse]
hide_when_typing = true

[colors.primary]
background = "#000000"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14.0
